### PR TITLE
Change id to id1 for creature queries

### PR DESCRIPTION
**Pull request by Hacki95**
Fixes: https://github.com/azerothcore/mod-progression-system/issues/111

Untested

### CODE REVIEW

**Comment by Hacki95** [comment]
@temperrr Test this one please. If you put it on the highest bracket and let it run through there should be no more errors.

**Comment by temperrr** [comment]
testing

**Comment by temperrr** [comment]
Tested, worked as described

**Comment by Hacki95** [comment]
> image

Fixed

**Comment by temperrr** [comment]
testing

**Comment by temperrr** [comment]
Possibly not the scope of this pr, but:

image
 is the next error.

**Comment by temperrr** [comment]
image

**Comment by temperrr** [comment]
image

**Comment by temperrr** [comment]
image

**Comment by temperrr** [comment]
image

**Comment by temperrr** [comment]
image

**Comment by temperrr** [comment]
image

**Comment by temperrr** [comment]
testing concluded

**Pull request merged**
