### PR TITLE
feat: add exchange NPC

### PR DESCRIPTION
**Pull request by 55Honey**
Transfer of the files from https://github.com/55Honey/Acore_ExchangeNpc to the progression repo as requested by Hacki.

Closes https://github.com/azerothcore/mod-progression-system/issues/61

### CODE REVIEW

**Comment by 55Honey** [comment]
Actually, there is an issue with the removal of all the mats now. We should make it so all ratios are 1:1 to allow for an easier revert before BC launches.

**Comment by 55Honey** [comment]
We currently give 
- 4 Primal Shadow for 1 Black Diamond and
- 1 Primal Air for 2 Essence of Air

Would it be appropriate from an economic perspective to change these to
- 1 Mote of Shadow for 1 Ichor of Undeath and
- 1 Mote of Air for 1 Elemental Air?

**Comment by 55Honey** [comment]
Adjusted all ratios and added a one-time query to execute when BC hits. No longer WIP. Can be tested/merged.

**Comment by 55Honey** [comment]
Sidenote: Not sure if we want this in the progression repo anyway. It's all in https://github.com/55Honey/Acore_ExchangeNpc atm

**Comment by Helias** [comment]
I think we could keep it separate and make some link
@Yehonal

**Pull request closed without merging**
