### PR TITLE
Redo Ahune Ice Stone progression script.

### PR DESCRIPTION
**Pull request by heyitsbench**
Did not test this, no idea if it works.

Aims to close https://github.com/chromiecraft/chromiecraft/issues/7140.

### CODE REVIEW

**Comment by heyitsbench** [comment]
CC: @Nyeriah

**Comment by heyitsbench** [comment]
Tested with what I assume the config looks like for CC, seems to work fine.

**Comment by heyitsbench** [comment]
Build failing due to core issue it looks like, not sure what/if I can do about it.

**Comment by Stump876** [comment]
This is not working properly. Ahune does not have his [shield](https://www.wowhead.com/tbc/spell=45954/ahunes-shield) when initially spawned. Making it a straight easy tank and spank for the first few minutes. If he does submerge and expose the core, afterwards he will emerge with the shield and mechanics work as they should. 
Heroics versions are also able to be farmed. Defeating Ahune does not save you to the instance. He also can be farmed indefinitely as long as the 5 dungeon resets per hour is observed.
image

**Comment by heyitsbench** [comment]
> Ahune does not have his [shield](https://www.wowhead.com/tbc/spell=45954/ahunes-shield) when initially spawned.

Should be fixed by https://github.com/azerothcore/azerothcore-wotlk/commit/c28a0973a2e5381309c9aaa1fa887b6d8c9070dc.

> Heroics versions are also able to be farmed. Defeating Ahune does not save you to the instance. He also can be farmed indefinitely as long as the 5 dungeon resets per hour is observed.

I don't believe this behavior was introduced by this PR, and the method for summoning is different between the current behavior (at 70 bracket) and TBC behavior, as the summon required a quest item in TBC and it does not in Wrath afaik.

**Pull request merged**
