### PR TITLE
feat: add PvP vendor items with related reputation for AB/WSG/AB

### PR DESCRIPTION
**Pull request by Helias**
Co-author: @temperrr @Hacki95

### CODE REVIEW

**Comment by temperrr** [comment]
30498 should be exalted requirement for horde wsg
19308 should be exalted for horde av and alliance av

30497 should be exalted requirement for alliance wsg

**Comment by temperrr** [comment]
The epic pvp set items should be moved up to the AQ bracket +-

**Comment by Helias** [comment]
Moved, and updated with main branch.

**Comment by temperrr** [comment]
wsg for alliance and horde vendor stop talking to me when I am exalted now

**Comment by Helias** [comment]
teleport yourself to a new zone like `stormwind` or to `gmisland` and use `.recall` to come back to the vendor, you'll get a zone-map reset that resets you some cache

**Comment by Helias** [comment]
updated req rep for AV to honored, increased honor price of epic items

**Comment by temperrr** [comment]
Tested, all good!

**Pull request merged**
