### PR TITLE
Set All 50-59 PvP items Extendend cost to 5k honor

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
https://github.com/azerothcore/mod-progression-system/issues/174

@FrancescoBorzi Is this the right way or do I have to create a new file?

Screenshot_20220224_091318

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@IntelligentQuantum no, we need this change to happen in another bracket.

In https://github.com/azerothcore/mod-progression-system/tree/main/src every folder is a different phase of the progression: https://www.chromiecraft.com/progression/

we changed those prices in the Bracket_50_59_A phase, now we need to change them again in another phase. So in a different directory.

@Nefertumm can you please make sure all devs understand correctly how our progression work, because this is very important for the project.

Also I think we need to write somewhere in this repo which phase from our Progression page corresponds to which Folder, because I find it a bit confusing as well.

cc @Hacki95 @Nyeriah @55Honey to get more help

**Comment by FrancescoBorzi** [comment]
cc @temperrr @Helias too

**Comment by 55Honey** [comment]
https://github.com/azerothcore/mod-progression-system/tree/main/src/Bracket_60_2_A/sql/world
This is the BWL bracket, i guess it belongs there?

**Comment by Nefertumm** [comment]
I already talked to him, he is going to open another PR tomorrow about this. :) Or well, he can also revert this changes and push the other ones here as well! Whatever you want to do, it's ok.

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
