### PR TITLE
Satchel 50 loot restore and satchel 55 will contain 50 loot

### PR DESCRIPTION
**Pull request by temperrr**
Removed 49 satchel from custom rdf satchel as it should be availible

Fixes: https://github.com/chromiecraft/chromiecraft/issues/2288 

(when one-time querry below is executed)

- [ ] Please review the querry below:

```
-- restore Satchel of Helpful Goods loot (50)

DELETE FROM `item_loot_template` WHERE `Entry` IN (52002, 52003);
INSERT INTO `item_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(52002, 1, 10046, 100, 0, 1, 1, 1, 1, 'Satchel of Helpful Goods - (ReferenceTable)'),
(52002, 2, 10047, 100, 0, 1, 2, 1, 1, 'Satchel of Helpful Goods - (ReferenceTable)'),
(52002, 3, 10048, 100, 0, 1, 3, 1, 1, 'Satchel of Helpful Goods - (ReferenceTable)'),
(52002, 4, 10049, 100, 0, 1, 4, 1, 1, 'Satchel of Helpful Goods - (ReferenceTable)');

-- remove both gold rewards
UPDATE `item_template` SET `minMoneyLoot` = 0, `maxMoneyLoot` = 0 WHERE `Entry` IN (52002, 52003);
```

### CODE REVIEW

**Comment by 55Honey** [comment]
I think the Restoration of 52002 should be a one-time query for CC only and doesn't need to be in the repo. We should Just make it that it's Not gonna be changed at all for Future progression servers Here.

**Comment by temperrr** [comment]
Ok I changed the PR for this.

**Comment by temperrr** [comment]
1 time querry
`-- restore Satchel of Helpful Goods loot (50)
DELETE FROM `item_loot_template` WHERE `Entry` IN (52002);
INSERT INTO `item_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(52002, 1, 10046, 100, 0, 1, 1, 1, 1, 'Satchel of Helpful Goods - (ReferenceTable)'),
(52002, 2, 10047, 100, 0, 1, 2, 1, 1, 'Satchel of Helpful Goods - (ReferenceTable)'),
(52002, 3, 10048, 100, 0, 1, 3, 1, 1, 'Satchel of Helpful Goods - (ReferenceTable)'),
(52002, 4, 10049, 100, 0, 1, 4, 1, 1, 'Satchel of Helpful Goods - (ReferenceTable)');

UPDATE `item_template` SET `minMoneyLoot` = 0, `maxMoneyLoot` = 0 WHERE `Entry` IN (52002);`

**Review by Hacki95 — APPROVED** [review]
Looks good!

**Comment by 55Honey** [comment]
Let's add the 52002 loot to the 52003 loot as well instead of giving gold. No more xp-locks are required to get BIS items that way.

**Comment by Hacki95** [comment]
What happened to this?

**Comment by 55Honey** [comment]
I'm not sure how it works, but i think we're missing that the 55 satchel contains the 45 items as well instead of gold.

**Comment by temperrr** [comment]
So this PR needs to be updated so both contain the 45 items?

**Comment by temperrr** [comment]
I dont know how to resolve that conflicting file error

**Comment by Hacki95** [comment]
I would just copy your changes and open the PR again. Probably the quickest way.

**Comment by Helias** [comment]
I solved them for you, hope I did it correctly, check the file changed ;-)

**Review by Helias — APPROVED** [review]

**Comment by 55Honey** [comment]
This changes/deletes a LOT of files. Is this intended? I think it should be only 1 or 2 .SQL files?

**Comment by temperrr** [comment]
Ah yes, I need to remove the 55 part from the one time query and add it to the custom SQL . I'll do it tomorrow

**Comment by temperrr** [comment]
Note to self I should refrain from making db SQLs haha

**Comment by 55Honey** [comment]
> This changes/deletes a LOT of files. Is this intended? I think it should be only 1 or 2 .SQL files?

I'm not sure what I've seen, but it showed like 150ish changed files to me last time I checked, while it's only 2 now. Disregard.

**Comment by temperrr** [comment]
This pr is not ready as I think I am just handling it all wrong. Maybe we have to ask a proper SQL maker for this and close this one. Don't want to break chromiecraft

**Comment by Helias** [comment]
The last commit that I did is cherry-pick from the master branch, so that big list of changed files is something that has been made in the master branch, not here, to see and to be sure the current changing of this PR you only need to check the "Files changed" here https://github.com/azerothcore/mod-progression-system/pull/55/files if what you see in these 2 files changed is what you want to apply on mod-progression-system you are safe ;-)

For what I see before and after my commit, what we have in this PR is correct ✅

**Pull request merged**
